"""add questionnaire waitlist and user models

Revision ID: a7b10e8ef6ef
Revises:
Create Date: 2026-10-07 03:46:44.880806

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7b10e8ef6ef"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionnaires",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questionnaires_slug"), "questionnaires", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_country_code", sa.String(length=4), nullable=True),
        sa.Column("phone_region", sa.String(length=2), nullable=True),
        sa.Column("phone_national", sa.String(length=20), nullable=True),
        sa.Column("phone_e164", sa.String(length=16), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "INACTIVE", "ACTIVE", "SUSPENDED", "DEACTIVATED", "DELETED", name="user_status"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone_e164"), "users", ["phone_e164"], unique=True)
    op.create_index(op.f("ix_users_phone_region"), "users", ["phone_region"], unique=False)
    op.create_table(
        "waitlist_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone_country_code", sa.String(length=4), nullable=True),
        sa.Column("phone_region", sa.String(length=2), nullable=True),
        sa.Column("phone_national", sa.String(length=20), nullable=True),
        sa.Column("phone_e164", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waitlist_entries_email"), "waitlist_entries", ["email"], unique=True)
    op.create_index(op.f("ix_waitlist_entries_phone_e164"), "waitlist_entries", ["phone_e164"], unique=True)
    op.create_index(op.f("ix_waitlist_entries_phone_region"), "waitlist_entries", ["phone_region"], unique=False)
    op.create_table(
        "questionnaire_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("waitlist_entry_id", sa.UUID(), nullable=True),
        sa.Column("completed_gate", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["questionnaire_id"], ["questionnaires.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["waitlist_entry_id"], ["waitlist_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questionnaire_sessions_questionnaire_id"), "questionnaire_sessions", ["questionnaire_id"], unique=False)
    op.create_index(op.f("ix_questionnaire_sessions_user_id"), "questionnaire_sessions", ["user_id"], unique=False)
    op.create_index(op.f("ix_questionnaire_sessions_waitlist_entry_id"), "questionnaire_sessions", ["waitlist_entry_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("placeholder", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("options", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["questionnaire_id"], ["questionnaires.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_questionnaire_id"), "questions", ["questionnaire_id"], unique=False)
    op.create_table(
        "answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("answer_array", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["questionnaire_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_answers_question_id"), "answers", ["question_id"], unique=False)
    op.create_index(op.f("ix_answers_session_id"), "answers", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answers_session_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_question_id"), table_name="answers")
    op.drop_table("answers")
    op.drop_index(op.f("ix_questions_questionnaire_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_questionnaire_sessions_waitlist_entry_id"), table_name="questionnaire_sessions")
    op.drop_index(op.f("ix_questionnaire_sessions_user_id"), table_name="questionnaire_sessions")
    op.drop_index(op.f("ix_questionnaire_sessions_questionnaire_id"), table_name="questionnaire_sessions")
    op.drop_table("questionnaire_sessions")
    op.drop_index(op.f("ix_waitlist_entries_phone_region"), table_name="waitlist_entries")
    op.drop_index(op.f("ix_waitlist_entries_phone_e164"), table_name="waitlist_entries")
    op.drop_index(op.f("ix_waitlist_entries_email"), table_name="waitlist_entries")
    op.drop_table("waitlist_entries")
    op.drop_index(op.f("ix_users_phone_region"), table_name="users")
    op.drop_index(op.f("ix_users_phone_e164"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_questionnaires_slug"), table_name="questionnaires")
    op.drop_table("questionnaires")
    # ### end Alembic commands ###
